### ISSUE TITLE
Moya version now out of date

### ISSUE THREAD

**Issue by AlexQuinlivan** [spxrogers/Moya-Gloss#10]
The major version of Moya is now 7.

See: https://github.com/Moya/Moya/releases/tag/7.0.0

**Comment by spxrogers** [comment]
hey @AlexQuinlivan, thanks for the issue plus a PR to fix it too!! I follow Moya and have been meaning to do this, I just have to look into specific release diffs since it's a major upgrade and _could_ have breaking changes. I highly doubt it since I only really use `mapJSON`

but I'll verify no ickyness in the morning and merge 😁😄

**Comment by AlexQuinlivan** [comment]
Cool, yeah seems to work with branch. Only needed immediately because of the new multipart support. Cheers 😄!

**Comment by spxrogers** [comment]
+CocoaPod (plus Carthage) update is now live.

cc: @AlexQuinlivan
