### ISSUE TITLE
Support for RxMoya.Response in RxMoyaGloss

### ISSUE THREAD

**Issue by AndrewSB** [spxrogers/Moya-Gloss#8]
Right now Observable+Gloss applies where the observable element is a Moya Response (`public extension ObservableType where E == Response`) - Response is short hand for `Moya.Response`

There are a couple of issues with setting up a custom provider to work with RxMoya. (https://github.com/Moya/Moya/issues/487)

Can it be made so the extension on Observable applies whenever the element is of type `RxMoya.Response` || `Moya.Response`?

**Comment by AndrewSB** [comment]
I've currently added https://gist.github.com/AndrewSB/1c24f094c5257ef7218a8b3bdc730b6a to my project - to get it working for now.

Would love to get the functionality built into RxMoyaGloss, so it works in my implementation :)

**Comment by AndrewSB** [comment]
@spxrogers would love to get this functionality built in so I can get rid of my fork!

**Comment by spxrogers** [comment]
<img width="882" alt="screen shot 2016-07-12 at 1 15 02 am" src="https://cloud.githubusercontent.com/assets/7064929/16755790/36a3807a-47ce-11e6-80bc-db8928d1f837.png">

working on this. (month later, yes sorry 👎 to me). it's not so straight-forward as including this extension. since Moya-Gloss is a CocoaPod hacked together to support Carthage, there is a weird state of supporting both build integrations. above shows a cocoapod-related error after integrating this and building fine with the carthage-related project (don't want to break CocoaPods to fix Carthage if you know what i mean). i'm going to have to investigate a solution where this extension only builds if it detects the RxMoya framework imported. sadly, i'm a bit rusty on all that Xcode build config stuff, but it is on my radar.

cc: @AndrewSB

**Comment by spxrogers** [comment]
@AndrewSB hey man, i'm digging this up from the grave. i super apologize that this fell completely off my radar. 

is this still an issue with the latest releases? i'm not a heavy carthage user so don't know any updates in that realm that might have resolved any transient errors.

**Comment by AndrewSB** [comment]
nah, don't worry about it! The [gist](https://gist.github.com/AndrewSB/1c24f094c5257ef7218a8b3bdc730b6a) I wrote has been doing its job since 😄 

At some point I may refactor the app that uses it and add a PR to this project, but hopefully I finish up https://github.com/Moya/Moya/pull/563 soon and then this won't be an issue 👍

**Comment by spxrogers** [comment]
alrighty, sounds good to me 👍 I'll close for now, don't hesitate to open anything new if something looks funny

always open for a PR to make it more Carthage friendly :)
